services:
  api01: &api
    build:
      context: .
      target: base
    container_name: api01
    hostname: api01
    volumes:
      - .:/app 
      - rubygems:/usr/local/bundle
    working_dir: /app
    networks:
      - payment-processor
      - backend
    command: ruby server.rb

  api02: 
    <<: *api
    container_name: api02
    hostname: api02

  worker:
    <<: *api
    container_name: worker
    hostname: worker
    command: ruby worker.rb

  redis:
    image: redis:7-alpine
    container_name: redis
    hostname: redis
    ports:
      - 6379:6379
    networks:
      - backend

  nginx:
    image: nginx 
    container_name: nginx
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 9999:9999
    networks:
      - backend
    depends_on:
      - redis
      - api01
      - api02
      - worker

volumes:
  rubygems:
networks:
  payment-processor:
    external: true
  backend:
